# Generated by Django 5.2.7 on 2025-10-27 20:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_remove_usuario_email_remove_usuario_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion opcional', null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'CATEGORIA',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion opcional', null=True)),
                ('precio', models.IntegerField(help_text='Precio unitario en pesos')),
                ('stock_disponible', models.IntegerField(default=0, help_text='Stock actual disponible en inventario')),
                ('categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'PRODUCTO',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_cambio', models.IntegerField(help_text='Positivo para entrada, negativo para salida')),
                ('motivo', models.CharField(choices=[('COMPRA', 'Compra de proveedor'), ('VENTA', 'Venta a cliente (Reserva)'), ('AJUSTE', 'Ajuste manual de stock'), ('DEVOLUCION', 'Devolucion de cliente'), ('MERMA', 'Merma o perdida')], max_length=50)),
                ('fecha_movimiento', models.DateField(default=django.utils.timezone.now)),
                ('empleado', models.ForeignKey(db_column='id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empleado')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'MOVIMIENTO_INVENTARIO',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_disponible__gte', 0)), name='stock_no_negativo'),
        ),
    ]
