# Generated by Django 5.2.6 on 2025-11-21 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, help_text='Ruta/URL o contenido de la imagen en formato texto', null=True)),
                ('orden', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
                'db_table': 'PRODUCTO_IMAGEN',
                'ordering': ['orden'],
            },
        ),
    ]
