# Generated by Django 5.2.6 on 2025-12-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_productoimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Si se marca, aparecerá en la página principal'),
        ),
    ]
