# Generated by Django 5.2.7 on 2025-10-27 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0002_remove_usuario_email_remove_usuario_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_reserva', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empleado')),
                ('usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RESERVA',
                'ordering': ['-fecha_reserva'],
            },
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField(help_text='Precio unitario en pesos al momento de la reserva')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.reserva')),
            ],
            options={
                'db_table': 'DETALLE_RESERVA',
                'unique_together': {('reserva', 'producto')},
            },
        ),
    ]
