# Generated by ChatGPT
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0002_alter_reserva_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="ultima_actividad",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
