# Generated by Django 5.2.6 on 2025-11-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_email_remove_usuario_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
