# Generated by Django 5.2.6 on 2025-11-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='referencia',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
