# Generated by Django 5.2.6 on 2025-11-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='referencia',
        ),
    ]
