# Generated by Django 5.2.6 on 2025-11-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_direccion_referencia_alter_usuario_last_login'),
        ('usuarios', '0006_alter_usuario_apellido_paterno_alter_usuario_rut_and_more'),
    ]

    operations = [
    ]
